spring.application.name=transaction-service

server.port=0
server.servlet.context-path=/api

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/transaction_db
spring.datasource.username=postgres
spring.datasource.password=ismayilov10
spring.jpa.properties.javax.persistence.validation.mode = none

# Consul
spring.cloud.consul.discovery.register=true
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=transaction-service
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${server.port}:${random.value}

