spring.application.name=replay-service

server.port=0
server.servlet.context-path=/api

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/replay_db
spring.datasource.username=postgres
spring.datasource.password=ismayilov10
spring.jpa.properties.javax.persistence.validation.mode = none


spring.kafka.consumer.bootstrap-serversCustomer=localhost:9092,localhost:9094


# Consul
spring.cloud.consul.discovery.register=true
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=account-service
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${server.port}:${random.value}


